---
version: 2.1

executors:
  node:
    parameters:
      tag:
        type: string
        default: latest
    working_directory: ~/build
    docker:
      - image: node:<< parameters.tag >>

references:
  build: &build
    steps:
      - run:
          name: Install Alpine Linux build dependencies
          command: |
            if [[ -f /sbin/apk ]]; then
              apk add --no-cache ca-certificates git openssh-client
            fi
      - checkout
      - run:
          name: Save build versions
          command: |
            echo "node: ${NODE_VERSION}" >> .versions
            echo "yarn: ${YARN_VERSION}" >> .versions
            if [[ -f /sbin/apk ]]; then
              echo "alpine: $(cat /etc/alpine-release)" >> .versions
            fi
            cat .versions
      - restore_cache:
          key: yarn-cache-{{ arch }}-{{ checksum ".versions" }}-
      - restore_cache:
          key: node-modules-{{ arch }}-{{ checksum ".versions" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Set yarn cache
          command: yarn config set cache-folder $HOME/.yarn-cache
      - run:
          name: Add npm authentication token
          command: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-cache-{{ arch }}-{{ checksum ".versions" }}-{{ epoch }}
          paths: ~/.yarn-cache
      - save_cache:
          key: node-modules-{{ arch }}-{{ checksum ".versions" }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - run:
          name: Test package
          command: |
            if [[ "${TEST_PACKAGE}" == 'true' ]]; then
              yarn test
            fi
      - run:
          name: Build package
          command: |
            if [[ "${BUILD_PACKAGE}" == 'true' ]]; then
              yarn run build
            fi
      - run:
          name: Upload coverage to Codecov
          command: |
            if [[ "${COVERAGE}" == 'true' && -n "${CODECOV_TOKEN}" ]]; then
              yarn global add codecov
              codecov
            fi
      - deploy:
          name: Publish package
          command: |
            if [[ "${PUBLISH_PACKAGE}" == 'true' ]]; then
              .circleci/publish.sh
            fi

jobs:
  node:
    executor:
      name: node
    environment:
      TEST_PACKAGE: 'true'
    <<: *build
  node-alpine:
    executor:
      name: node
      tag: alpine
    environment:
      TEST_PACKAGE: 'true'
    <<: *build
  node-carbon:
    executor:
      name: node
      tag: carbon
    environment:
      TEST_PACKAGE: 'true'
      BUILD_PACKAGE: 'true'
      COVERAGE: 'true'
    <<: *build
  node-carbon-alpine:
    executor:
      name: node
      tag: carbon-alpine
    environment:
      TEST_PACKAGE: 'true'
    <<: *build
  publish:
    executor:
      name: node
      tag: carbon
    environment:
      BUILD_PACKAGE: 'true'
      PUBLISH_PACKAGE: 'true'
    <<: *build

workflows:
  default:
    jobs:
      - node
      - node-alpine
      - node-carbon
      - node-carbon-alpine
      - publish:
          filters:
            branches:
              only: /^(v(er)?\/?[0-9].*|master)/
          requires:
            - node
            - node-alpine
            - node-carbon
            - node-carbon-alpine
